// flow-typed signature: 107e0b65db8e45dfe35ed1f61d390e7b
// flow-typed version: <<STUB>>/normalize.css_v4.2.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'normalize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'normalize.css' {
  declare module.exports: any;
}
